# TODO: Add versions to images
version: "3"
services:
  wordpress:
    image: wordpress
  mariadb:
    image: mariadb
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
