- name: Install dependencies
  hosts: all
  tasks:
    - name: Install docker apt repository dependencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true
    - name: Copy docker repository setter
      copy:
        src: setup-docker-repository.sh
        dest: /tmp/
    - name: Set up docker repository
      command: sh /tmp/setup-docker-repository.sh
    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: true
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: true
    - name: Install docker and docker-compose python pkg
      pip:
        name:
          - docker
          - docker-compose
        state: present

- name: Deploy website
  hosts: all
  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: site/
        dest: /site/
    - name: Set good ownership
      file:
        path: /site/docker-entrypoint.sh
        group: root
        owner: root
    - name: Stop website
      docker_compose:
        project_src: /site
        state: absent
    - name: Start website
      docker_compose:
        project_src: /site/
        state: present
