# TODO: Add versions to images
version: "3"
services:
  wordpress:
    image: wordpress
    env_file:
      - wordpress.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    restart: unless-stopped
  mariadb:
    build: mariadb
    env_file:
      - mariadb/mariadb.env
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    restart: unless-stopped

volumes:
  wordpress-data:
  wordpress-db:
